version: '3.7'

services:
  tempo:
    image: grafana/tempo:1.0.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./etc/tempo-local.yaml:/etc/tempo.yaml
      - ./data/tempo-data:/tmp/tempo
    ports:
      - "14268" # jaeger ingest, Jaeger - Thrift HTTP
      - "14250" # Jaeger - GRPC
      - "55680" # OpenTelemetry
      - "3100" # tempo
      - "6831/udp" # Jaeger - Thrift Compact
      - "6832/udp" # Jaeger - Thrift Binary

  loki:
    image: grafana/loki:2.2.1
    command: -config.file=/etc/loki/loki-local.yaml
    ports:
      - "3101:3100" # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    volumes:
      - ./etc/loki-local.yaml:/etc/loki/loki-local.yaml
      - ./data/loki-data:/tmp/loki

  grafana:
    image: grafana/grafana:8.1.0-ubuntu
    volumes:
      - ./data/grafana-data/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana-data/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./data/grafana-data/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      # - prometheus
      - tempo
      - loki
      # - volume_exporter
